require_relative "Piece"
require_relative "King"
require_relative "NullPiece"
require_relative "Rook"
require_relative "Knight"
require_relative "Pawn"
require_relative "Bishop"
require_relative "Queen"